# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTitleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editTitleWindow(object):
    def setupUi(self, editTitleWindow):
        editTitleWindow.setObjectName("editTitleWindow")
        editTitleWindow.resize(263, 89)
        self.buttonBox = QtWidgets.QDialogButtonBox(editTitleWindow)
        self.buttonBox.setGeometry(QtCore.QRect(30, 50, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.editTitleInputField = QtWidgets.QLineEdit(editTitleWindow)
        self.editTitleInputField.setGeometry(QtCore.QRect(60, 17, 191, 21))
        self.editTitleInputField.setObjectName("editTitleInputField")
        self.label = QtWidgets.QLabel(editTitleWindow)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label.setObjectName("label")

        self.retranslateUi(editTitleWindow)
        self.buttonBox.accepted.connect(editTitleWindow.accept)
        self.buttonBox.rejected.connect(editTitleWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(editTitleWindow)

    def retranslateUi(self, editTitleWindow):
        _translate = QtCore.QCoreApplication.translate
        editTitleWindow.setWindowTitle(_translate("editTitleWindow", "Edit title"))
        self.label.setText(_translate("editTitleWindow", "Title:"))
