# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MoveVideoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_moveVideoWindow(object):
    def setupUi(self, moveVideoWindow):
        moveVideoWindow.setObjectName("moveVideoWindow")
        moveVideoWindow.resize(312, 90)
        self.buttonBox = QtWidgets.QDialogButtonBox(moveVideoWindow)
        self.buttonBox.setGeometry(QtCore.QRect(30, 50, 271, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.foldersComboBox = QtWidgets.QComboBox(moveVideoWindow)
        self.foldersComboBox.setGeometry(QtCore.QRect(130, 17, 171, 26))
        self.foldersComboBox.setObjectName("foldersComboBox")
        self.label = QtWidgets.QLabel(moveVideoWindow)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label.setObjectName("label")

        self.retranslateUi(moveVideoWindow)
        self.buttonBox.accepted.connect(moveVideoWindow.accept)
        self.buttonBox.rejected.connect(moveVideoWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(moveVideoWindow)

    def retranslateUi(self, moveVideoWindow):
        _translate = QtCore.QCoreApplication.translate
        moveVideoWindow.setWindowTitle(_translate("moveVideoWindow", "Move video.."))
        self.label.setText(_translate("moveVideoWindow", "Choose new folder:"))
