# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewFolderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newFolderWindow(object):
    def setupUi(self, newFolderWindow):
        newFolderWindow.setObjectName("newFolderWindow")
        newFolderWindow.resize(323, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newFolderWindow.sizePolicy().hasHeightForWidth())
        newFolderWindow.setSizePolicy(sizePolicy)
        newFolderWindow.setMinimumSize(QtCore.QSize(323, 100))
        newFolderWindow.setMaximumSize(QtCore.QSize(323, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(newFolderWindow)
        self.buttonBox.setGeometry(QtCore.QRect(30, 60, 281, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.newFolderInputField = QtWidgets.QLineEdit(newFolderWindow)
        self.newFolderInputField.setGeometry(QtCore.QRect(100, 20, 211, 21))
        self.newFolderInputField.setObjectName("newFolderInputField")
        self.label = QtWidgets.QLabel(newFolderWindow)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(newFolderWindow)
        self.buttonBox.accepted.connect(newFolderWindow.accept)
        self.buttonBox.rejected.connect(newFolderWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(newFolderWindow)

    def retranslateUi(self, newFolderWindow):
        _translate = QtCore.QCoreApplication.translate
        newFolderWindow.setWindowTitle(_translate("newFolderWindow", "New folder"))
        self.label.setText(_translate("newFolderWindow", "Folder name:"))
